# Generated by Django 2.1.5 on 2019-05-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Notice',
        ),
    ]
